# Explicit Nixpacks configuration for Node.js 18 to avoid auto-detection issues

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[variables]
NODE_ENV = "production"
NIXPACKS_NODE_VERSION = "18"

# Completely skip all automatic phases to prevent npm-9_x detection
[phases.install]
cmds = ["echo 'Skipping install phase'"]

[phases.build]
cmds = ["echo 'Skipping build phase'"]

[start]
cmd = "bash start-for-easypanel.sh"