# Nixpacks configuration for Excel to Cosmos DB Dashboard

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[variables]
NODE_ENV = "production"

[phases.install]
cmds = [
    "npm ci --only=production",
    "cd server && npm ci --only=production && cd .."
]

[phases.build]
cmds = [
    "npm run build:client",
    "cd server && npm run build && cd .."
]

[start]
cmd = "bash start-for-easypanel.sh"