# Nixpacks configuration for Excel to Cosmos DB Dashboard

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[variables]
NODE_ENV = "production"
NIXPACKS_NODE_VERSION = "18"

# Skip the install phase to avoid conflicts
[phases.install]
skip = true

# Skip the build phase to avoid conflicts
[phases.build]
skip = true

[start]
cmd = "bash start-for-easypanel.sh"