# Nixpacks configuration for Excel to Cosmos DB Dashboard

# Setup phase - ensure we have the right environment
[phases.setup]
nixPkgs = [
    "nodejs_18",
    "npm"
]

# Setup environment variables
[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

# Install phase - install dependencies for both frontend and backend
[phases.install]
cmds = [
    # Ensure Node.js and npm are available
    "echo 'Checking Node.js and npm availability...'",
    "which node && node --version",
    "which npm && npm --version",
    # Clean any existing modules to prevent conflicts
    "rm -rf node_modules server/node_modules",
    # Install root dependencies
    "npm ci --only=production --prefer-online",
    # Install missing Vite dependencies that might be needed for build
    "npm install @vitejs/plugin-react vite --save-dev",
    # Install server dependencies
    "cd server && npm ci --only=production --prefer-online && cd .."
]

# Build phase - build both frontend and backend
[phases.build]
cmds = [
    # Build frontend
    "npm run build:client",
    # Build backend
    "cd server && npm run build && cd .."
]

# Start command for the application
[start]
cmd = "bash start-for-easypanel.sh"