# Nixpacks configuration for Excel to Cosmos DB Dashboard

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[variables]
NODE_ENV = "production"
NIXPACKS_SKIP_NPM_INSTALL = "1"

# Skip the install phase
[phases.install]
skip = true

# Skip the build phase
[phases.build]
skip = true

[start]
cmd = "bash start-for-easypanel.sh"