# Use a custom build script
[build]
script = ".nixpacks/build.sh"

# The start command will be used when the container runs
[start]
cmd = "./start-for-easypanel.sh"

# Disable default phases since we're using a custom build script
[phases]
setup = { nixPkgs = [] }
install = { cmds = [] }
build = { cmds = [] }
