# Specify the base image and system packages
[phases.setup]
nixPkgs = [
    'nodejs_18',
    'npm',
    'python3',
    'make',
    'g++',
    'curl'
]

# Setup environment variables
[phases.setupEnvironment]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

# Install phase
[phases.install]
cmds = [
    "echo 'Using Node.js version:' && node --version",
    "echo 'Using npm version:' && npm --version",
    "npm install"
]

# Build phase - build both frontend and backend
[phases.build]
cmds = [
    "npm run build:client",
    "cd server && npm install && npm run build && cd .."
]

# Start command for the application
[start]
cmd = "bash start-for-easypanel.sh"

# Define the output directory for the build
[build]
  base = "."
  builder = "nixpacks"
  publish = "."

# Enable experimental features if needed
[experimental]
  nix = true
