# Specify the base image and system packages
[phases.setup]
nixPkgs = [
    'nodejs-18.x',
    'python3',
    'make',
    'g++',
    'curl',
    'gnupg',
    'ca-certificates',
    'lsb-release'
]

# Install phase
[phases.install]
cmds = [
    "echo 'Using Node.js version:' && node --version",
    "echo 'Using npm version:' && npm --version"
]

# Build phase - use our custom build script
[phases.build]
cmds = ["bash .nixpacks/build.sh"]

# Start command for the application
[start]
cmd = "./start-for-easypanel.sh"

# Environment variables
[phases.setupEnvironment]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

# Define the output directory for the build
[build]
  base = "."
  builder = "nixpacks"
  publish = "deploy_output"

# Enable experimental features if needed
[experimental]
  nix = true
