version: '3.8'

services:
  excel-etl-app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=production
      # Azure Cosmos DB settings
      - AZURE_COSMOS_ENDPOINT=${AZURE_COSMOS_ENDPOINT}
      - AZURE_COSMOS_KEY=${AZURE_COSMOS_KEY}
      - AZURE_COSMOS_DATABASE=${AZURE_COSMOS_DATABASE}
      - AZURE_COSMOS_CONTAINER=${AZURE_COSMOS_CONTAINER}
      # Azure Storage settings
      - AZURE_STORAGE_ACCOUNT=${AZURE_STORAGE_ACCOUNT}
      - AZURE_STORAGE_KEY=${AZURE_STORAGE_KEY}
      - AZURE_STORAGE_CONTAINER=${AZURE_STORAGE_CONTAINER}
      # Add any other environment variables your application needs
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped