name: Dependency Updates

on:
  schedule:
    # Run dependency updates every Monday at 6 AM UTC
    - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  dependency-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install npm-check-updates
        run: npm install -g npm-check-updates

      - name: Check for outdated dependencies
        run: |
          echo "Checking for outdated dependencies..."
          ncu -u
          npm install

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: update dependencies'
          body: |
            ## Dependency Updates
            This PR updates project dependencies to their latest versions.
            
            Please review and test before merging.
          branch: dependency-updates
          delete-branch: true