# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# Fixed deployment path issues for Linux App Service - 2025-08-18
# Fixed npm ci issues - 2025-08-18
# Switched back to npm install from npm ci - 2025-08-18

name: Build and deploy Node.js app to Azure Web App - excel-etl-backend-378680

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
      - '.github/workflows/main_excel-etl-backend-378680.yml'
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'
  AZURE_WEBAPP_NAME: 'excel-etl-backend-378680'
  AZURE_WEBAPP_PACKAGE_PATH: 'server/.'
  RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP || 'IESR-DB' }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install server dependencies
      working-directory: server
      run: |
        npm install
        
    - name: Build the app
      working-directory: server
      run: |
        npm run build
        
    - name: Run Cosmos DB connection test
      working-directory: server
      env:
        NODE_OPTIONS: --experimental-vm-modules
        COSMOS_ENDPOINT: ${{ secrets.AZURE_COSMOS_ENDPOINT }}
        COSMOS_KEY: ${{ secrets.AZURE_COSMOS_KEY }}
        COSMOS_DATABASE: ${{ secrets.AZURE_COSMOS_DATABASE }}
        COSMOS_CONTAINER: ${{ secrets.AZURE_COSMOS_CONTAINER }}
      run: |
        echo "Testing Cosmos DB connection..."
        npx tsx scripts/test-cosmos-direct.ts
        
    - name: Install production dependencies
      working-directory: server
      run: |
        npm install --omit=dev
        
    - name: Prepare deployment artifact
      run: |
        mkdir -p deployment
        # Create a proper package.json for Azure App Service
        echo '{
          "name": "excel-upload-server",
          "version": "1.0.0",
          "description": "Server for Excel file upload and processing",
          "main": "dist/src/server.js",
          "type": "module",
          "scripts": {
            "start": "node --enable-source-maps dist/src/server.js",
            "build": "tsc -p tsconfig.build.json"
          },
          "engines": {
            "node": ">=16.0.0"
          }
        }' > deployment/package.json
        cp server/package-lock.json deployment/
        cp -r server/dist deployment/
        cd deployment
        npm install --omit=dev
        
    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v4
      with:
        name: node-app
        path: deployment
        retention-days: 1

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app
        
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'Production'
        package: .
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      env:
        NODE_ENV: production
        
    - name: 'Verify deployment'
      run: |
        echo "✅ Deployment completed successfully!"
        echo "Your app should be available at: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
        echo ""
        echo "If you encounter any issues, please check:"
        echo "1. The GitHub Actions workflow logs"
        echo "2. The Azure App Service logs in the Azure Portal"
